parameters:
#    pantarei_user.example.class: Pantarei\Bundle\UserBundle\Example

services:
#    pantarei_user.example:
#        class: %pantarei_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
