<?php

/**
 * This file is part of the pantarei/user-bundle package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pantarei\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pantarei\User\Model\UserInterface;
use Pantarei\User\Model\UserManagerInterface;
use Symfony\Component\Security\Core\User\UserInterface as AbstractUserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserManagerInterface
{
    public function getClass()
    {
        return $this->getClassName();
    }   

    public function createUser()
    {
        $class = $this->getClass();
        return new $class();
    }

    public function deleteUser(UserInterface $user)
    {
        $this->getEntityManager()->remove($user);
        $this->getEntityManager()->flush();
    }

    public function reloadUser(UserInterface $user)
    {
        $this->getEntityManager()->refresh($user);
    }

    public function updateUser(UserInterface $user)
    {
        $this->getEntityManager()->presist($user);
        $this->getEntityManager()->flush();
    }

    public function findUserByUsername($username)
    {
        return $this->findOneBy(array(
            'username' => $username,
        ));
    }

    public function loadUserByUsername($username)
    {
        return $this->findUserByUsername($username);
    }

    public function refreshUser(AbstractUserInterface $user)
    {
        return $this->reloadUser($user);
    }

    public function supportsClass($class)
    {
        return $this->getEntityName() === $class
            || is_subclass_of($class, $this->getEntityName());
    }
}
